import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/first-trace',
        'getting-started/process-mining',
        'getting-started/adding-guards',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/architecture',
        'guides/dashboard',
        'guides/otel',
        'guides/python',
        'guides/storage',
        'guides/adapters',
        'guides/deployment',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
      link: undefined,
    },
    'faq',
    'glossary',
    {
      type: 'category',
      label: 'Experimental',
      items: [
        'experimental/soma/overview',
        'experimental/soma/concepts',
        'experimental/soma/getting-started',
        'experimental/soma/roadmap',
      ],
    },
  ],
};

export default sidebars;
